# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Фотография в удовльствие
email: ioksha@gmail.com
description: >
  Детский фотограф в Минске.
baseurl: "/volha.photo" # the subpath of your site, e.g. /blog
url: "http://VolhaHarabchuk.github.io" # the base hostname & protocol for your site
github_username:  VolhaHarabchuk

# Build settings
markdown: kramdown
